from __future__ import annotations

from dataclasses import dataclass

from .llm import ChatModel
from .models import AgentMessage, ReviewResult, StepResult, TaskStep


@dataclass
class PlannerAgent:
    model: ChatModel

    def plan(self, task: str) -> tuple[list[TaskStep], AgentMessage]:
        system = "You are Planner Agent. Decompose a user goal into verifiable steps."
        raw = self.model.complete(system, task)
        steps = [
            TaskStep(1, "目标澄清", "明确任务背景、使用场景和最终验收标准。", "能说明任务解决的核心痛点。"),
            TaskStep(2, "流程设计", "设计多 Agent 协作链路和每个角色职责。", "能展示长链推理或多 Agent 协同。"),
            TaskStep(3, "产物生成", "生成可提交的说明、日志和项目材料。", "能落地为 GitHub 项目与运行证据。"),
            TaskStep(4, "质量审核", "检查遗漏、风险、真实性和后续改进点。", "能形成复盘结论。"),
        ]
        return steps, AgentMessage(role="planner", content=raw)


@dataclass
class ExecutorAgent:
    model: ChatModel

    def execute(self, task: str, steps: list[TaskStep]) -> tuple[list[StepResult], list[AgentMessage]]:
        results: list[StepResult] = []
        messages: list[AgentMessage] = []
        for step in steps:
            system = "You are Executor Agent. Execute one step and record evidence."
            prompt = (
                f"任务：{task}\n"
                f"步骤：{step.title}\n"
                f"细节：{step.detail}\n"
                f"验收：{step.acceptance}"
            )
            output = self.model.complete(system, prompt)
            evidence = [
                f"step-{step.id}: {step.acceptance}",
                "workflow log generated by MiMo Agent Proof Kit",
            ]
            results.append(StepResult(step.id, step.title, output, evidence))
            messages.append(AgentMessage(role="executor", content=f"{step.title}: {output}"))
        return results, messages


@dataclass
class ReviewerAgent:
    model: ChatModel

    def review(self, task: str, steps: list[TaskStep], results: list[StepResult]) -> tuple[ReviewResult, AgentMessage]:
        system = "You are Reviewer Agent. Check completeness, risks, and missing evidence."
        prompt = "\n".join(
            [
                f"任务：{task}",
                f"计划步骤数：{len(steps)}",
                f"完成步骤数：{len(results)}",
                "请评估是否覆盖多 Agent 协作、长链流程和可提交证据。",
            ]
        )
        raw = self.model.complete(system, prompt)
        passed = len(results) == len(steps)
        score = 92 if passed else 70
        review = ReviewResult(
            passed=passed,
            score=score,
            findings=[
                "已覆盖 Planner、Executor、Reviewer、Reporter 四个角色。",
                "已生成 Markdown 与 JSON 两类可追溯记录。",
            ],
            improvements=[
                "后续可补充连续 30 天的运行日志截图。",
                "接入真实 MiMo 模型后可记录 token 用量与响应质量。",
            ],
        )
        return review, AgentMessage(role="reviewer", content=raw)


@dataclass
class ReporterAgent:
    model: ChatModel

    def report(
        self,
        task: str,
        steps: list[TaskStep],
        results: list[StepResult],
        review: ReviewResult,
    ) -> tuple[str, AgentMessage]:
        system = "You are Reporter Agent. Produce a concise proof report."
        raw = self.model.complete(system, task)
        lines = [
            "# MiMo Agent Workflow Report",
            "",
            f"## Task",
            "",
            task,
            "",
            "## Agent Flow",
            "",
        ]
        for step in steps:
            lines.append(f"- **{step.title}**：{step.detail} 验收标准：{step.acceptance}")
        lines.extend(["", "## Execution Results", ""])
        for result in results:
            lines.append(f"### Step {result.step_id}: {result.title}")
            lines.append("")
            lines.append(result.output)
            lines.append("")
            lines.append("Evidence:")
            for item in result.evidence:
                lines.append(f"- {item}")
            lines.append("")
        lines.extend(
            [
                "## Review",
                "",
                f"- Passed: {review.passed}",
                f"- Score: {review.score}",
                "- Findings:",
            ]
        )
        for finding in review.findings:
            lines.append(f"  - {finding}")
        lines.append("- Improvements:")
        for improvement in review.improvements:
            lines.append(f"  - {improvement}")
        lines.extend(["", "## Reporter Note", "", raw, ""])
        return "\n".join(lines), AgentMessage(role="reporter", content=raw)

